from __future__ import annotations

"""Column contract for property_data_final.csv (joined + scored)."""

FINAL_COLUMNS = [
    "listing_code",
    "listing_url",
    "source",
    "status",
    "title",
    "address",
    "district_key",
    "town_name",
    "state_district_name",
    "state_region_name",
    "sqm",
    "rooms",
    "storey",
    "storeys",
    "price_raw",
    "price_currency_iso",
    "price_byn",
    "price_usd",
    "price_per_sqm_usd",
    "fx_rate_used",
    "published_at",
    "updated_at",
    "published_at_raw",
    "updated_at_raw",
    "days_on_market",
    "lon",
    "lat",
    "dist_m_metro",
    "dist_m_park",
    "dist_m_water",
    "active_count_district",
    "archived_count_district",
    "turnover_ratio",
    "city_avg_turnover",
    "velocity_bonus",
    "desirability_score",
    "scraped_at",
]
